ARG BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.6.1
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gnupg \
        ca-certificates \
        apt-transport-https \
        software-properties-common \
        curl \
        lsb-release

# install ROS melodic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ros-melodic-ros-base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python-rosdep \
        python-rosinstall \
        python-rosinstall-generator \
        python-wstool \
        build-essential

# install ROS sensor pacakge
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ros-melodic-joint-state-publisher \
        ros-melodic-usb-cam \
        ros-melodic-realsense2-camera \
        ros-melodic-image-transport* \
        ros-melodic-rgbd-launch \
        ros-melodic-rplidar-ros

# external ROS setting
WORKDIR /root
RUN mkdir -p external_catkin_ws/src && \
    cd external_catkin_ws/src && \
    git clone https://github.com/autonomylab/create_robot.git -b melodic && \
    cd /root/external_catkin_ws && \
    bash -c "source /opt/ros/melodic/setup.bash; rosdep init; rosdep update" && \
    apt-get update && \
    bash -c "source /opt/ros/melodic/setup.bash; rosdep install --from-paths src -i -r -y" && \
    bash -c "source /opt/ros/melodic/setup.bash; catkin_make"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gstreamer1.0-tools libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev

RUN cd external_catkin_ws/src && \
    git clone https://github.com/ros-drivers/gscam.git && \
    cd /root/external_catkin_ws/src/gscam && \
    sed -e "s/EXTRA_CMAKE_FLAGS = -DUSE_ROSBUILD:BOOL=1$/EXTRA_CMAKE_FLAGS = -DUSE_ROSBUILD:BOOL=1 -DGSTREAMER_VERSION_1_x=On/" -i Makefile && \
    cd /root/external_catkin_ws/ && \
    bash -c "source /opt/ros/melodic/setup.bash; catkin_make"

WORKDIR /root/

COPY ./docker/scripts/. /root/scripts/
RUN chmod -R +x /root/scripts/*

RUN echo "source /root/scripts/initialize-bash-shell.sh" > /root/.bashrc

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT []

CMD ["/bin/bash"]
