ARG L4T_VERSION="r32.5.0"
FROM nvcr.io/nvidia/l4t-base:${L4T_VERSION}

ENV DEBIAN_FRONTEND noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gnupg \
        ca-certificates \
        apt-transport-https \
        software-properties-common \
        curl \
        lsb-release

# install ROS melodic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ros-melodic-ros-base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python-rosdep \
        python-rosinstall \
        python-rosinstall-generator \
        python-wstool \
        build-essential

# install ROS sensor pacakge
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ros-melodic-joint-state-publisher \
        ros-melodic-usb-cam \
        ros-melodic-rplidar-ros

# external ROS setting
WORKDIR /root
RUN mkdir -p external_catkin_ws/src && \
    cd external_catkin_ws/src && \
    git clone https://github.com/autonomylab/create_robot.git -b melodic && \
    cd /root/external_catkin_ws && \
    bash -c "source /opt/ros/melodic/setup.bash; rosdep init; rosdep update" && \
    apt-get update && \
    bash -c "source /opt/ros/melodic/setup.bash; rosdep install --from-paths src -i -r -y" && \
    bash -c "source /opt/ros/melodic/setup.bash; catkin_make"

WORKDIR /root/

COPY ./docker/scripts/. /root/scripts/
RUN chmod -R +x /root/scripts/*

RUN echo "source /root/scripts/initialize-bash-shell.sh" > /root/.bashrc

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT []

CMD ["/bin/bash"]
